apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-directory
spec:
  destination:
    namespace: directory
    server: https://kubernetes.default.svc
  project: default
  source:
    path: directoryOfMnifests
    repoURL: https://github.com/emiakia/argocd.git
    targetRevision: main
    
